### ISSUE TITLE
./run.sh fails

### ISSUE THREAD

**Issue by hakunaMatataHub** [raffraffraff/nvidia-sdkmanager#1]
My configuration of host computer : UBUNTU 20.04 LTS

Gtk-Message: 14:11:29.133: Failed to load module "canberra-gtk-module"

**Comment by raffraffraff** [comment]
DISCLAIMER: I no longer have a Jetson board, so I could only confirm that this worked as far as the "Host Components" installation.

I ran through the whole process documented in the README.md, on a brand new laptop that had no NVIDIA software installed. I also used a new NVIDIA Developer account that I created for the purpose of testing. I noticed 3 things, any one of which could trip you up:

1. My `run.sh` script presumed that the docker mounted files and directories already exist. If they do, great. if they _don't_ then docker will create them as 'root', which means that they will have wrong ownership, and `~/.nvidia-settings-rc` will be assumed to be a _directory_ instead of a _file_. 
2. Creating an NVIDIA Developer account and logging in is a pain. If you chose to create your account using Facebook/Google login, you won't be able to log the NVIDIA SDK Manager into the Developer portal because it seems to _require_ a password. (I had to log in separately and send myself a password reset)
3. When you run the NVIDIA SDK Manager docker container and it prompts you to log in, _use QR Code URL_! Copy the URL and launch it in a browser that is already logged into the NVIDIA Developer portal. 

I have updated the `build.sh` and `README.md`, but before you retry, you should check that ~/.nvidia-settings-rc is not a directory, and the directories 'nvidia' and '.nvsdkm' are not owned by root
